name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60

    defaults:
      run:
        working-directory: content-build

    steps:
      - name: Checkout vagov-content
        uses: actions/checkout@v2
        with:
          path: vagov-content

      - name: Checkout content-build
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/content-build
          path: content-build

      - name: Get Node version
        id: get-node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}

      - name: Install dependencies & Build
        uses: nick-invision/retry@v2
        with:
          command: pwd && ls && cd content-build && yarn install --frozen-lockfile --prefer-offline && yarn fetch-drupal-cache && yarn build --buildtype=vagovprod --asset-source=local
          max_attempts: 3
          timeout_minutes: 7
        env:
          NODE_ENV: production

      # - name: Build
      #   run:  cd content-build && yarn fetch-drupal-cache && yarn build --buildtype=vagovprod --asset-source=local
      #   env:
      #     NODE_ENV: production
  
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Node version
        id: get-node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}

      - name: Audit dependencies
        run: yarn security-check
