name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60

    defaults:
      run:
        working-directory: content-build

    steps:
      - name: Checkout vagov-content
        uses: actions/checkout@v2
        with:
          path: vagov-content

      - name: Checkout content-build
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/content-build
          path: content-build

      - name: Checkout vets-website
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/vets-website
          path: vets-website

      - name: Get Node version
        id: get-node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}

      - name: Install dependencies and build vets-website
        uses: nick-invision/retry@v2
        with:
          command: cd vets-website && yarn --frozen-lockfile --prefer-offline && yarn build
          max_attempts: 3
          timeout_minutes: 15

      - name: Install dependencies and build content-build
        uses: nick-invision/retry@v2
        with:
          command: cd content-build && cp .env.example .env && yarn --frozen-lockfile --prefer-offline && yarn fetch-drupal-cache && yarn build
          max_attempts: 3
          timeout_minutes: 45
  
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/workflows/install
        timeout-minutes: 30
        with:
          key: ${{ hashFiles('yarn.lock') }}
          yarn_cache_folder: .cache/yarn
          path: |
            .cache/yarn
            node_modules

      - name: List changed files
        id: changed-files
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo ::set-output name=all_changed_files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          else
            echo ::set-output name=all_changed_files::$(git diff --name-only origin/master...)
          fi

      - name: Get app entries for changed files
        id: get-changed-apps
        run: echo ::set-output name=app_entries::$(node script/github-actions/get-changed-apps.js)
        env:
          CHANGED_FILE_PATHS: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Audit dependencies
        if: steps.get-changed-apps.outputs.app_entries == ''
        run: yarn security-check